### ISSUE TITLE
cryptkeeper examples fails on latest build 

### ISSUE THREAD

**Issue by spleonard1** [barricklab/cryptkeeper#3]
Deleting my old crypt keeper install and build a new environment with fresh install after pulling from repository. End of failed command below, let me know if you want the log or anything

cryptkeeper -i pSMART-LCKan-BPMV1.fna -o pSMART-LCKan-BPMV1

.....
[2023-03-16 13:50:32,413] Cryptkeeper: Running ORF prediction
Traceback (most recent call last):
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/bin/cryptkeeper", line 8, in <module>
    sys.exit(main())
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/cryptkeeper.py", line 87, in main
    result = cryptkeeper(input_file = options.i,
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/cryptkeeper.py", line 361, in cryptkeeper
    rbs_predictions = ostir(input_file_name)
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/dependency_wrappers.py", line 29, in ostir
    findings_forward = run_ostir(forward_seq, verbosity=0)
TypeError: run_ostir() got an unexpected keyword argument 'verbosity'

**Comment by spleonard1** [comment]
I redid a fresh cryptkeeper install based on instructions for conda. It still failed, but in a different way! I tried with the most up to do date ostir installed from GitHub.

(cryptkeeper) houtx11:BPMV leonard28$ cryptkeeper -i pSMART-LCKan-BPMV1.fna -o pSMART-LCKan-BPMV1
[2023-07-14 17:17:25,984] Cryptkeeper: Running RhoTermPredict
[2023-07-14 17:17:26,645] Cryptkeeper: Running RIT_predict_TransTerm
[2023-07-14 17:17:26,730] Cryptkeeper: Running TSS_predict_promoter_calculator
[2023-07-14 17:23:44,732] Cryptkeeper: Running ORF prediction
[2023-07-14 17:23:44,992] Cryptkeeper: Running RBS prediction
Traceback (most recent call last):
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/bin/cryptkeeper", line 8, in <module>
    sys.exit(main())
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/cryptkeeper.py", line 98, in main
    result = cryptkeeper(input_file = options.i,
  File "/Users/leonard28/miniconda3/envs/cryptkeeper/lib/python3.9/site-packages/cryptkeeper/cryptkeeper.py", line 385, in cryptkeeper
    rbs_predictions = ostir(input_file_name, threads=threads)
TypeError: ostir() got an unexpected keyword argument 'threads'

**Comment by croots** [comment]
Resolved with cf66904
